### ISSUE TITLE
Jihoon Test Codes for Lab 8: Cryptography

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm/UVACS1110-#20]

**Comment by jeongm-in** [comment]
I ran code and got this error
```
Traceback (most recent call last):
File "/Users/jeongminlim/PycharmProjects/UVACS1110-/sogogibeef/test.py", line 3, 
in <module> from . import crypto as c
ValueError: Attempted relative import in non-package
 ```

When __init__.py was added to directory

```
Traceback (most recent call last):
 File "/Users/jeongminlim/PycharmProjects/UVACS1110-/sogogibeef/test.py", line 2, in <module>
 from . import crypto as c
ValueError: Attempted relative import in non-package
```

when "from ." was removed
```
/usr/bin/python /Users/jeongminlim/PycharmProjects/UVACS1110-/sogogibeef/test.py

Process finished with exit code 0
```

**Comment by Bartleby2718** [comment]
project interpreter의 문제로 추정되어 바꿔봤지만 확실하지는 않음
`python -m unittest filename`의 방식으로 run함으로써 해결 가능하므로 close
